channels:
  - pytorch
#  - nvidia  # uncomment for pytorch with cuda
  - ilastik-forge
  - conda-forge
  - nodefaults
dependencies:
  - python 3.9.*
  - numpy 1.21.*
  - appdirs
  - cachetools
  - dpct
  - fastfilters
  - future
  - greenlet
  - grpcio 1.41.*
  - h5py
  - hytra
  - ilastik-feature-selection
  - ilastikrag >=0.1.4
  - ilastiktools
  - jsonschema
  - mamutexport
  - marching_cubes
  - ndstructs
  - nifty
  - pandas
  - psutil
  - pyopengl
  - pyqt 5.15.*
  - pyqtgraph
  # previous versions would set thread limits globally with side effects
  - python-elf >= 0.4.8
  - qimage2ndarray
  - scikit-image
  - scikit-learn
  # for python 3.7 compatible environment use
  # tiffile >2020.9.22,<=2021.11.2
  - tifffile
  # build 1.11.1=*_1028 on cf is the first to be compatible with numpy>1.19
  # need to bump this manually until there is a true version bump in vigra 
  # DECREMENTED FOR SH DEP
  - vigra 1.11.1=*_1032
  - xarray
  - z5py

  # Spherical harmonics dependencies
  - pyshtools 
  - blosc <=1.21.0 # not sure if necessary
  - numba
  - ducc0 # not necessary until python version bump

  # Neural Network Workflow dependencies
  # can be changed to request gpu versions
  - pytorch 1.13.*
  - cpuonly  # comment out for pytorch with cuda
  # mamba does not "respect" track_features, which is the idea behind cpuonly,
  # with ilastik-pytorch-version-helper-cpu we help mamba on linux and windows
  # to install a cpu-build
  - ilastik-pytorch-version-helper-cpu  # comment out for pytorch with cuda
  # - pytorch-cuda=11.3  # uncomment for pytorch with cuda, specify cuda version

  - tiktorch >=23.7.0

  # dev-only dependencies
  - conda-build
  - mypy
  - pre-commit
  - pytest >4
  - pytest-qt

  # ensure working environment on apple M1 via rosetta
  # remove once native builds are available
  # - mkl 2021.*  # [osx]
